class AppLocalizations {
  static const Map<String, Map<String, String>> _t = {
    'en': {
      'appTitle': 'LingoLens AI',
      'scanText': 'Scan Text',
      'about': 'About',
      'aboutDesc': 'LingoLens AI extracts text from images, detects language, and translates it instantly.',
      'chooseImageSource': 'Choose Image Source',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'settings': 'Settings',
      'darkMode': 'Dark Mode',
      'appLanguage': 'App Language',
      'soundEffects': 'Sound Effects',
      'vibration': 'Vibration',
      'scanResults': 'Scan Results',
      'detectedLanguage': 'Detected Language',
      'originalText': 'Original Text',
      'translateTo': 'Translate To',
      'translate': 'Translate',
      'translationFailed': 'Translation failed:',
      'noTextDetected': 'No text detected.',
      'lang_en': 'English',
      'lang_fr': 'French',
      'lang_ar': 'Arabic',
    },
    'fr': {
      'appTitle': 'LingoLens AI',
      'scanText': 'Scanner le texte',
      'about': 'À propos',
      'aboutDesc': "LingoLens AI extrait le texte des images, détecte la langue et le traduit instantanément.",
      'chooseImageSource': 'Choisir la source',
      'camera': 'Caméra',
      'gallery': 'Galerie',
      'settings': 'Paramètres',
      'darkMode': 'Mode sombre',
      'appLanguage': "Langue de l'app", 
      'soundEffects': 'Effets sonores',
      'vibration': 'Vibration',
      'scanResults': 'Résultats de l’analyse',
      'detectedLanguage': 'Langue détectée',
      'originalText': 'Texte original',
      'translateTo': 'Traduire en',
      'translate': 'Traduire',
      'translationFailed': 'Échec de la traduction:',
      'noTextDetected': 'Aucun texte détecté.',
      'lang_en': 'Anglais',
      'lang_fr': 'Français',
      'lang_ar': 'Arabe',
    },
    'ar': {
      'appTitle': 'LingoLens AI',
      'scanText': 'مسح النص',
      'about': 'حول',
      'aboutDesc': 'LingoLens AI يستخرج النص من الصور ويكشف اللغة ويترجمها فورًا.',
      'chooseImageSource': 'اختر مصدر الصورة',
      'camera': 'الكاميرا',
      'gallery': 'المعرض',
      'settings': 'الإعدادات',
      'darkMode': 'الوضع الداكن',
      'appLanguage': 'لغة التطبيق',
      'soundEffects': 'المؤثرات الصوتية',
      'vibration': 'الاهتزاز',
      'scanResults': 'نتائج المسح',
      'detectedLanguage': 'اللغة المكتشفة',
      'originalText': 'النص الأصلي',
      'translateTo': 'الترجمة إلى',
      'translate': 'ترجمة',
      'translationFailed': 'فشل الترجمة:',
      'noTextDetected': 'لم يتم اكتشاف نص.',
      'lang_en': 'الإنجليزية',
      'lang_fr': 'الفرنسية',
      'lang_ar': 'العربية',
    }
  };

  static Map<String, String> of(String langCode) {
    return _t[langCode] ?? _t['en']!;
  }
}
