// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM8SVLfXaItE4UtdisM2E18AVY4vGnWTM',
    appId: '1:209199959695:web:d28bc348e49b256d562afa',
    messagingSenderId: '209199959695',
    projectId: 'lingolens-app',
    authDomain: 'lingolens-app.firebaseapp.com',
    storageBucket: 'lingolens-app.firebasestorage.app',
    measurementId: 'G-MHD5MXM1QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq1mrKFdkBlK1HexnP3XaRpHcOVonTGNo',
    appId: '1:209199959695:android:5f09568ff1a31981562afa',
    messagingSenderId: '209199959695',
    projectId: 'lingolens-app',
    storageBucket: 'lingolens-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVtphKDUGwjiH5WGzrsDceoe76DkEsNlA',
    appId: '1:209199959695:ios:4fafef417a71f2cc562afa',
    messagingSenderId: '209199959695',
    projectId: 'lingolens-app',
    storageBucket: 'lingolens-app.firebasestorage.app',
    iosBundleId: 'com.example.lingolens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVtphKDUGwjiH5WGzrsDceoe76DkEsNlA',
    appId: '1:209199959695:ios:4fafef417a71f2cc562afa',
    messagingSenderId: '209199959695',
    projectId: 'lingolens-app',
    storageBucket: 'lingolens-app.firebasestorage.app',
    iosBundleId: 'com.example.lingolens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM8SVLfXaItE4UtdisM2E18AVY4vGnWTM',
    appId: '1:209199959695:web:e21d0a400c827c82562afa',
    messagingSenderId: '209199959695',
    projectId: 'lingolens-app',
    authDomain: 'lingolens-app.firebaseapp.com',
    storageBucket: 'lingolens-app.firebasestorage.app',
    measurementId: 'G-YGVGVNHWYY',
  );
}
